// Supabase Database Types
// This file will be auto-generated by Supabase CLI in production
// For now, we define the types manually based on the PRD

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'creative' | 'mentor' | 'employer' | 'investor'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          user_id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          bio: string | null
          role: UserRole
          skills: string[]
          location: string | null
          is_mentor: boolean
          is_available_for_mentorship: boolean
          max_mentees: number
          payment_provider: string | null
          payment_provider_id: string | null
          payment_account: string | null
          payment_account_verified: boolean
          payout_mode: 'auto' | 'wallet'
          stripe_account_id: string | null
          stripe_onboarding_complete: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          role?: UserRole
          skills?: string[]
          location?: string | null
          is_mentor?: boolean
          is_available_for_mentorship?: boolean
          max_mentees?: number
          payment_provider?: string | null
          payment_provider_id?: string | null
          payment_account?: string | null
          payment_account_verified?: boolean
          payout_mode?: 'auto' | 'wallet'
          stripe_account_id?: string | null
          stripe_onboarding_complete?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          role?: UserRole
          skills?: string[]
          location?: string | null
          is_mentor?: boolean
          is_available_for_mentorship?: boolean
          max_mentees?: number
          payment_provider?: string | null
          payment_provider_id?: string | null
          payment_account?: string | null
          payment_account_verified?: boolean
          payout_mode?: 'auto' | 'wallet'
          stripe_account_id?: string | null
          stripe_onboarding_complete?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      portfolios: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          tagline: string | null
          slug: string
          is_public: boolean
          is_featured: boolean
          view_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          tagline?: string | null
          slug: string
          is_public?: boolean
          is_featured?: boolean
          view_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string | null
          tagline?: string | null
          slug?: string
          is_public?: boolean
          is_featured?: boolean
          view_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          portfolio_id: string
          title: string
          description: string | null
          client_name: string | null
          project_date: string | null
          external_link: string | null
          tags: string[]
          images: string[]
          video_url: string | null
          display_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          portfolio_id: string
          title: string
          description?: string | null
          client_name?: string | null
          project_date?: string | null
          external_link?: string | null
          tags?: string[]
          images?: string[]
          video_url?: string | null
          display_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          portfolio_id?: string
          title?: string
          description?: string | null
          client_name?: string | null
          project_date?: string | null
          external_link?: string | null
          tags?: string[]
          images?: string[]
          video_url?: string | null
          display_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      posts: {
        Row: {
          id: string
          user_id: string
          content: string
          images: string[]
          video_url: string | null
          likes_count: number
          comments_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          content: string
          images?: string[]
          video_url?: string | null
          likes_count?: number
          comments_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          content?: string
          images?: string[]
          video_url?: string | null
          likes_count?: number
          comments_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      comments: {
        Row: {
          id: string
          post_id: string
          user_id: string
          parent_id: string | null
          content: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          post_id: string
          user_id: string
          parent_id?: string | null
          content: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          post_id?: string
          user_id?: string
          parent_id?: string | null
          content?: string
          created_at?: string
          updated_at?: string
        }
      }
      likes: {
        Row: {
          id: string
          post_id: string
          user_id: string
          created_at: string
        }
        Insert: {
          id?: string
          post_id: string
          user_id: string
          created_at?: string
        }
        Update: {
          id?: string
          post_id?: string
          user_id?: string
          created_at?: string
        }
      }
      post_reactions: {
        Row: {
          id: string
          post_id: string
          user_id: string
          reaction_type: 'like' | 'smile' | 'angry' | 'excited'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          post_id: string
          user_id: string
          reaction_type: 'like' | 'smile' | 'angry' | 'excited'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          post_id?: string
          user_id?: string
          reaction_type?: 'like' | 'smile' | 'angry' | 'excited'
          created_at?: string
          updated_at?: string
        }
      }
      comment_likes: {
        Row: {
          id: string
          comment_id: string
          user_id: string
          created_at: string
        }
        Insert: {
          id?: string
          comment_id: string
          user_id: string
          created_at?: string
        }
        Update: {
          id?: string
          comment_id?: string
          user_id?: string
          created_at?: string
        }
      }
      mentorship_requests: {
        Row: {
          id: string
          mentee_id: string
          mentor_id: string
          message: string
          skills_to_develop: string[]
          goals: string | null
          portfolio_id: string | null
          status: 'pending' | 'accepted' | 'declined'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          mentee_id: string
          mentor_id: string
          message: string
          skills_to_develop?: string[]
          goals?: string | null
          portfolio_id?: string | null
          status?: 'pending' | 'accepted' | 'declined'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          mentee_id?: string
          mentor_id?: string
          message?: string
          skills_to_develop?: string[]
          goals?: string | null
          portfolio_id?: string | null
          status?: 'pending' | 'accepted' | 'declined'
          created_at?: string
          updated_at?: string
        }
      }
      mentorships: {
        Row: {
          id: string
          mentee_id: string
          mentor_id: string
          request_id: string
          status: 'active' | 'paused' | 'completed'
          started_at: string
          ended_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          mentee_id: string
          mentor_id: string
          request_id: string
          status?: 'active' | 'paused' | 'completed'
          started_at?: string
          ended_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          mentee_id?: string
          mentor_id?: string
          request_id?: string
          status?: 'active' | 'paused' | 'completed'
          started_at?: string
          ended_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      opportunities: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string
          type: 'gig' | 'job' | 'investment'
          category: string
          budget_min: number | null
          budget_max: number | null
          currency: string
          location: string | null
          is_remote: boolean
          deadline: string | null
          start_date: string | null
          required_skills: string[]
          experience_level: 'junior' | 'mid-level' | 'senior' | null
          company_name: string | null
          attachments: string[]
          status: 'open' | 'closed' | 'filled'
          applications_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description: string
          type: 'gig' | 'job' | 'investment'
          category: string
          budget_min?: number | null
          budget_max?: number | null
          currency?: string
          location?: string | null
          is_remote?: boolean
          deadline?: string | null
          start_date?: string | null
          required_skills?: string[]
          experience_level?: 'junior' | 'mid-level' | 'senior' | null
          company_name?: string | null
          attachments?: string[]
          status?: 'open' | 'closed' | 'filled'
          applications_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string
          type?: 'gig' | 'job' | 'investment'
          category?: string
          budget_min?: number | null
          budget_max?: number | null
          currency?: string
          location?: string | null
          is_remote?: boolean
          deadline?: string | null
          start_date?: string | null
          required_skills?: string[]
          experience_level?: 'junior' | 'mid-level' | 'senior' | null
          company_name?: string | null
          attachments?: string[]
          status?: 'open' | 'closed' | 'filled'
          applications_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      applications: {
        Row: {
          id: string
          opportunity_id: string
          applicant_id: string
          portfolio_id: string | null
          cover_letter: string
          proposed_budget: number | null
          status: 'pending' | 'reviewing' | 'accepted' | 'rejected' | 'withdrawn'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          opportunity_id: string
          applicant_id: string
          portfolio_id?: string | null
          cover_letter: string
          proposed_budget?: number | null
          status?: 'pending' | 'reviewing' | 'accepted' | 'rejected' | 'withdrawn'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          opportunity_id?: string
          applicant_id?: string
          portfolio_id?: string | null
          cover_letter?: string
          proposed_budget?: number | null
          status?: 'pending' | 'reviewing' | 'accepted' | 'rejected' | 'withdrawn'
          created_at?: string
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          opportunity_id: string | null
          application_id: string | null
          payer_id: string
          payee_id: string
          amount: number
          currency: string
          platform_fee: number
          net_amount: number
          monime_checkout_session_id: string | null
          monime_payout_id: string | null
          monime_order_number: string | null
          payment_type: 'full' | 'partial_50' | 'pitch_investment'
          escrow_id: string | null
          pitch_investment_id: string | null
          stripe_payment_intent_id: string | null
          stripe_transfer_id: string | null
          status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'disputed'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          opportunity_id?: string | null
          application_id?: string | null
          payer_id: string
          payee_id: string
          amount: number
          currency?: string
          platform_fee: number
          net_amount: number
          monime_checkout_session_id?: string | null
          monime_payout_id?: string | null
          monime_order_number?: string | null
          payment_type?: 'full' | 'partial_50' | 'pitch_investment'
          escrow_id?: string | null
          pitch_investment_id?: string | null
          stripe_payment_intent_id?: string | null
          stripe_transfer_id?: string | null
          status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'disputed'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          opportunity_id?: string | null
          application_id?: string | null
          payer_id?: string
          payee_id?: string
          amount?: number
          currency?: string
          platform_fee?: number
          net_amount?: number
          monime_checkout_session_id?: string | null
          monime_payout_id?: string | null
          monime_order_number?: string | null
          payment_type?: 'full' | 'partial_50' | 'pitch_investment'
          escrow_id?: string | null
          pitch_investment_id?: string | null
          stripe_payment_intent_id?: string | null
          stripe_transfer_id?: string | null
          status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'disputed'
          created_at?: string
          updated_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          message: string
          data: Json | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          message: string
          data?: Json | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          title?: string
          message?: string
          data?: Json | null
          is_read?: boolean
          created_at?: string
        }
      }
      bookmarks: {
        Row: {
          id: string
          user_id: string
          portfolio_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          portfolio_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          portfolio_id?: string
          created_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          sender_id: string
          receiver_id: string
          subject: string
          content: string
          is_read: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          sender_id: string
          receiver_id: string
          subject?: string
          content: string
          is_read?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          sender_id?: string
          receiver_id?: string
          subject?: string
          content?: string
          is_read?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      mentorship_feedback: {
        Row: {
          id: string
          mentorship_request_id: string
          reviewer_id: string
          mentor_id: string
          rating: number
          feedback_text: string
          created_at: string
        }
        Insert: {
          id?: string
          mentorship_request_id: string
          reviewer_id: string
          mentor_id: string
          rating: number
          feedback_text?: string
          created_at?: string
        }
        Update: {
          id?: string
          mentorship_request_id?: string
          reviewer_id?: string
          mentor_id?: string
          rating?: number
          feedback_text?: string
          created_at?: string
        }
      }
      work_submissions: {
        Row: {
          id: string
          application_id: string
          opportunity_id: string
          creative_id: string
          employer_id: string
          message: string
          files: Json
          status: 'submitted' | 'revision_requested' | 'approved' | 'superseded' | 'payment_pending'
          feedback: string | null
          revision_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          application_id: string
          opportunity_id: string
          creative_id: string
          employer_id: string
          message?: string
          files?: Json
          status?: 'submitted' | 'revision_requested' | 'approved' | 'superseded' | 'payment_pending'
          feedback?: string | null
          revision_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          application_id?: string
          opportunity_id?: string
          creative_id?: string
          employer_id?: string
          message?: string
          files?: Json
          status?: 'submitted' | 'revision_requested' | 'approved' | 'superseded' | 'payment_pending'
          feedback?: string | null
          revision_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      pitch_investments: {
        Row: {
          id: string
          pitch_id: string
          investor_id: string
          recipient_id: string
          amount: number
          currency: string
          platform_fee: number
          net_payout_amount: number
          monime_checkout_session_id: string | null
          monime_order_number: string | null
          monime_payout_id: string | null
          status: 'awaiting_payment' | 'payment_received' | 'payout_initiated' | 'completed' | 'failed'
          payout_status: 'pending' | 'initiated' | 'completed' | 'failed'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          pitch_id: string
          investor_id: string
          recipient_id: string
          amount: number
          currency?: string
          platform_fee?: number
          net_payout_amount?: number
          monime_checkout_session_id?: string | null
          monime_order_number?: string | null
          monime_payout_id?: string | null
          status?: 'awaiting_payment' | 'payment_received' | 'payout_initiated' | 'completed' | 'failed'
          payout_status?: 'pending' | 'initiated' | 'completed' | 'failed'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          pitch_id?: string
          investor_id?: string
          recipient_id?: string
          amount?: number
          currency?: string
          platform_fee?: number
          net_payout_amount?: number
          monime_checkout_session_id?: string | null
          monime_order_number?: string | null
          monime_payout_id?: string | null
          status?: 'awaiting_payment' | 'payment_received' | 'payout_initiated' | 'completed' | 'failed'
          payout_status?: 'pending' | 'initiated' | 'completed' | 'failed'
          created_at?: string
          updated_at?: string
        }
      }
      delivery_escrows: {
        Row: {
          id: string
          submission_id: string
          application_id: string
          opportunity_id: string
          creative_id: string
          employer_id: string
          agreed_amount: number
          payment_amount: number
          payment_percentage: number
          currency: string
          monime_checkout_session_id: string | null
          monime_order_number: string | null
          monime_payout_id: string | null
          platform_fee: number
          net_payout_amount: number
          status:
            | 'awaiting_review'
            | 'review_approved'
            | 'awaiting_payment'
            | 'payment_received'
            | 'payout_initiated'
            | 'completed'
            | 'revision_exhausted_awaiting_payment'
            | 'partial_payment_received'
            | 'partial_payout_completed'
          files_released: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          submission_id: string
          application_id: string
          opportunity_id: string
          creative_id: string
          employer_id: string
          agreed_amount: number
          payment_amount: number
          payment_percentage?: number
          currency?: string
          monime_checkout_session_id?: string | null
          monime_order_number?: string | null
          monime_payout_id?: string | null
          platform_fee?: number
          net_payout_amount?: number
          status?:
            | 'awaiting_review'
            | 'review_approved'
            | 'awaiting_payment'
            | 'payment_received'
            | 'payout_initiated'
            | 'completed'
            | 'revision_exhausted_awaiting_payment'
            | 'partial_payment_received'
            | 'partial_payout_completed'
          files_released?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          submission_id?: string
          application_id?: string
          opportunity_id?: string
          creative_id?: string
          employer_id?: string
          agreed_amount?: number
          payment_amount?: number
          payment_percentage?: number
          currency?: string
          monime_checkout_session_id?: string | null
          monime_order_number?: string | null
          monime_payout_id?: string | null
          platform_fee?: number
          net_payout_amount?: number
          status?:
            | 'awaiting_review'
            | 'review_approved'
            | 'awaiting_payment'
            | 'payment_received'
            | 'payout_initiated'
            | 'completed'
            | 'revision_exhausted_awaiting_payment'
            | 'partial_payment_received'
            | 'partial_payout_completed'
          files_released?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      payment_webhook_events: {
        Row: {
          id: string
          provider: string
          event_id: string
          event_name: string
          object_id: string | null
          received_at: string
          payload: Json
        }
        Insert: {
          id?: string
          provider?: string
          event_id: string
          event_name: string
          object_id?: string | null
          received_at?: string
          payload: Json
        }
        Update: {
          id?: string
          provider?: string
          event_id?: string
          event_name?: string
          object_id?: string | null
          received_at?: string
          payload?: Json
        }
      }
      user_wallets: {
        Row: {
          id: string
          user_id: string
          currency: string
          available_balance: number
          pending_balance: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          currency?: string
          available_balance?: number
          pending_balance?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          currency?: string
          available_balance?: number
          pending_balance?: number
          created_at?: string
          updated_at?: string
        }
      }
      wallet_ledger: {
        Row: {
          id: string
          wallet_id: string
          user_id: string
          currency: string
          entry_type: 'credit' | 'debit' | 'hold' | 'release' | 'adjustment'
          amount: number
          available_delta: number
          pending_delta: number
          balance_after_available: number
          balance_after_pending: number
          source_type: 'delivery_escrow' | 'pitch_investment' | 'cashout_request' | 'system_adjustment'
          source_id: string | null
          idempotency_key: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          wallet_id: string
          user_id: string
          currency?: string
          entry_type: 'credit' | 'debit' | 'hold' | 'release' | 'adjustment'
          amount: number
          available_delta?: number
          pending_delta?: number
          balance_after_available: number
          balance_after_pending: number
          source_type: 'delivery_escrow' | 'pitch_investment' | 'cashout_request' | 'system_adjustment'
          source_id?: string | null
          idempotency_key?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          wallet_id?: string
          user_id?: string
          currency?: string
          entry_type?: 'credit' | 'debit' | 'hold' | 'release' | 'adjustment'
          amount?: number
          available_delta?: number
          pending_delta?: number
          balance_after_available?: number
          balance_after_pending?: number
          source_type?: 'delivery_escrow' | 'pitch_investment' | 'cashout_request' | 'system_adjustment'
          source_id?: string | null
          idempotency_key?: string | null
          metadata?: Json
          created_at?: string
        }
      }
      cashout_requests: {
        Row: {
          id: string
          user_id: string
          wallet_id: string
          currency: string
          amount: number
          provider: 'momo' | 'bank' | 'wallet'
          provider_id: string
          account_masked: string
          monime_payout_id: string | null
          status: 'pending' | 'initiated' | 'completed' | 'failed'
          failure_reason: string | null
          initiated_at: string | null
          completed_at: string | null
          failed_at: string | null
          idempotency_key: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          wallet_id: string
          currency?: string
          amount: number
          provider: 'momo' | 'bank' | 'wallet'
          provider_id: string
          account_masked: string
          monime_payout_id?: string | null
          status?: 'pending' | 'initiated' | 'completed' | 'failed'
          failure_reason?: string | null
          initiated_at?: string | null
          completed_at?: string | null
          failed_at?: string | null
          idempotency_key?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          wallet_id?: string
          currency?: string
          amount?: number
          provider?: 'momo' | 'bank' | 'wallet'
          provider_id?: string
          account_masked?: string
          monime_payout_id?: string | null
          status?: 'pending' | 'initiated' | 'completed' | 'failed'
          failure_reason?: string | null
          initiated_at?: string | null
          completed_at?: string | null
          failed_at?: string | null
          idempotency_key?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      wallet_backfill_receivables: {
        Args: {
          p_user_id: string
          p_currency?: string
        }
        Returns: {
          applied_count: number
          applied_amount: number
        }[]
      }
      wallet_apply_mutation: {
        Args: {
          p_user_id: string
          p_currency: string
          p_available_delta: number
          p_pending_delta: number
          p_entry_type: 'credit' | 'debit' | 'hold' | 'release' | 'adjustment'
          p_amount: number
          p_source_type: 'delivery_escrow' | 'pitch_investment' | 'cashout_request' | 'system_adjustment'
          p_source_id: string | null
          p_idempotency_key?: string | null
          p_metadata?: Json
        }
        Returns: string
      }
    }
    Enums: {
      user_role: UserRole
      opportunity_type: 'gig' | 'job' | 'investment'
      experience_level: 'junior' | 'mid-level' | 'senior'
      application_status: 'pending' | 'reviewing' | 'accepted' | 'rejected' | 'withdrawn'
      transaction_status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'disputed'
      mentorship_status: 'active' | 'paused' | 'completed'
      mentorship_request_status: 'pending' | 'accepted' | 'declined'
    }
  }
}

// Helper types for easier use
export type Profile = Database['public']['Tables']['profiles']['Row']
export type Portfolio = Database['public']['Tables']['portfolios']['Row']
export type Project = Database['public']['Tables']['projects']['Row']
export type Post = Database['public']['Tables']['posts']['Row']
export type Comment = Database['public']['Tables']['comments']['Row']
export type Like = Database['public']['Tables']['likes']['Row']
export type MentorshipRequest = Database['public']['Tables']['mentorship_requests']['Row']
export type Mentorship = Database['public']['Tables']['mentorships']['Row']
export type Opportunity = Database['public']['Tables']['opportunities']['Row']
export type Application = Database['public']['Tables']['applications']['Row']
export type Transaction = Database['public']['Tables']['transactions']['Row']
export type Notification = Database['public']['Tables']['notifications']['Row']
export type Bookmark = Database['public']['Tables']['bookmarks']['Row']
export type Message = Database['public']['Tables']['messages']['Row']
export type MentorshipFeedback = Database['public']['Tables']['mentorship_feedback']['Row']
export type WorkSubmission = Database['public']['Tables']['work_submissions']['Row']
export type PitchInvestment = Database['public']['Tables']['pitch_investments']['Row']
export type DeliveryEscrow = Database['public']['Tables']['delivery_escrows']['Row']
export type PaymentWebhookEvent = Database['public']['Tables']['payment_webhook_events']['Row']
export type UserWallet = Database['public']['Tables']['user_wallets']['Row']
export type WalletLedgerEntry = Database['public']['Tables']['wallet_ledger']['Row']
export type CashoutRequest = Database['public']['Tables']['cashout_requests']['Row']